insert into oscar(name,category,status,yearof)values
('RAMI MALEK-(Bohemian Rhapsody)','Actor','Winner',2019),
('CHRISTIAN BALE(Vice)','Actor','Nominee',2019),
('BRADLEY COOPER-A Star Is Born','Actor','Nominee',2019),
('WILLEM DAFOE (At Eternity Gate)','Actor','Nominee',2019),
('VIGGO MORTENSEN (Green Book)','Actor','Nominee',2019),
('OLIVIA COLMAN (The Favourite)','Actress','Winner',2019),
('YALITZA APARICIO (Roma)','Actress','Nominee',2019),
('GLENN CLOSE (The Wife)','Actress','Nominee',2019),
('LADY GAGA (A Star Is Born)','Actress','Nominee',2019),
('MELISSA MCCARTHY (Can You Ever Forgive Me?)','Actress','Nominee',2019),
('ROMA (Alfonso Cuarón)','Cinematography','Winner',2019),
('COLD WAR (Łukasz Żal)','Cinematography','Nominee',2019),
('THE FAVOURITE (Robbie Ryan)','Cinematography','Nominee',2019),
('NEVER LOOK AWAY (Caleb Deschanel)','Cinematography','Nominee',2019),
('A STAR IS BORN (Matthew Libatique)','Cinematography','Nominee',2019),
('Alfonso Cuarón (ROMA)','Director','Winner',2019),
('Spike Lee (BLACKKKLANSMAN)','Director','Nominee',2019),
('Paweł Pawlikowski (COLD WAR)','Director','Nominee',2019),
('Yorgos Lanthimos (THE FAVOURITE)','Director','Nominee',2019),
('Adam McKay (VICE)','Director','Nominee',2019),
('SHALLOW (A Star Is Born)','Music','Winner',2019),
('ALL THE STARS (Black Panther)','Music','Nominee',2019),
('I WLL FIGHT (RBG)','Music','Nominee',2019),
('THE PLACE WHERE LOST THINGS GO (Mary Poppins Returns)','Music','Nominee',2019),
('WHEN A COWBOY TRADES HIS SPURS FOR WINGS (The Ballad of Buster Scruggs)','Music','Nominee',2019),
('FIRST MAN (Paul Lambert, Ian Hunter, Tristan Myles and J.D. Schwalm)','Visual Effects','Winner',2019),
('AVENGERS: INFINITY WAR (Dan DeLeeuw, Russell Earl, Matt Aitken and Dan Sudick)','Visual Effects','Nominee',2019),
('CHRISTOPHER ROBIN (Christopher Lawrence, Michael Eames, Theo Jones and Chris Corbould)','Visual Effects','Nominee',2019),
('READY PLAYER ONE (Roger Guyett, Grady Cofer, Matthew E. Butler and David Shirk)','Visual Effects','Nominee',2019),
('SOLO: A STAR WARS STORY (Rob Bredow, Patrick Tubach, Neal Scanlan and Dominic Tuohy)','Visual Effects','Nominee',2019),
('FREE SOLO','Documentary','Winner',2019),
('HALE COUNTY THIS MORNING, THIS EVENING','Documentary','Nominee',2019),
('MINDING THE GAP','Documentary','Nominee',2019),
('OF FATHERS AND SONS','Documentary','Nominee',2019),
('RBG','Documentary','Nominee',2019),
('GREEN BOOK','Movie','Winner',2019),
('BLACK PANTHER','Movie','Nominee',2019),
('BLACKKKLANSMAN','Movie','Nominee',2019),
('BOHEMIAN RHAPSODY','Movie','Nominee',2019),
('THE FAVOURITE','Movie','Nominee',2019),
('ROMA','Movie','Nominee',2019),
('A STAR IS BORN','Movie','Nominee',2019),
('VICE','Movie','Nominee',2019),
('JOAQUIN PHOENIX (Joker)','Actor','Winner',2020),
('ANTONIO BANDERAS (Pain and Glory)','Actor','Nominee',2020),
('LEONARDO DICAPRIO (Once upon a Time...in Hollywood)','Actor','Nominee',2020),
('ADAM DRIVER (Marriage Story)','Actor','Nominee',2020),
('JONATHAN PRYCE (The Two Popes)','Actor','Nominee',2020),
('RENÉE ZELLWEGER (Judy)','Actress','Winner',2020),
('CYNTHIA ERIVO (Harriet)','Actress','Nominee',2020),
('SCARLETT JOHANSSON (Marriage Story)','Actress','Nominee',2020),
('SAOIRSE RONAN (Little Women)','Actress','Nominee',2020),
('CHARLIZE THERON (Bombshell)','Actress','Nominee',2020),
('1917 (Roger Deakins)','Cinematography','Winner',2020),
('THE IRISHMAN (Rodrigo Prieto)','Cinematography','Nominee',2020),
('JOKER (Lawrence Sher)','Cinematography','Nominee',2020),
('THE LIGHTHOUSE (Jarin Blaschke)','Cinematography','Nominee',2020),
('ONCE UPON A TIME...IN HOLLYWOOD (Robert Richardson)','Cinematography','Nominee',2020),
('Bong Joon Ho (PARASITE)','Director','Winner',2020),
('Bong Joon Ho (Bong Joon Ho)','Director','Nominee',2020),
('Todd Phillips (JOKER)','Director','Nominee',2020),
('Sam Mendes (1917)','Director','Nominee',2020),
('Quentin Tarantino (ONCE UPON A TIME...IN HOLLYWOOD)','Director','Nominee',2020),
('LOVE ME AGAIN (Rocketman)','Music','Winner',2020),
('I CANT LET YOU THROW YOURSELF AWAY (Toy Story 4)','Music','Nominee',2020),
('I AM STANDING WITH YOU (Breakthrough)','Music','Nominee',2020),
('INTO THE UNKNOWN (Frozen II)','Music','Nominee',2020),
('STAND UP (Harriet)','Music','Nominee',2020),
('1917 (Guillaume Rocheron, Greg Butler and Dominic Tuohy)','Visual Effects','Winner',2020),
('AVENGERS: ENDGAME (Dan DeLeeuw, Russell Earl, Matt Aitken and Dan Sudick)','Visual Effects','Nominee',2020),
('THE IRISHMAN (Pablo Helman, Leandro Estebecorena, Nelson Sepulveda-Fauser and Stephane Grabli)','Visual Effects','Nominee',2020),
('THE LION KING (Robert Legato, Adam Valdez, Andrew R. Jones and Elliot Newman)','Visual Effects','Nominee',2020),
('STAR WARS: THE RISE OF SKYWALKER (Roger Guyett, Neal Scanlan, Patrick Tubach and Dominic Tuohy)','Visual Effects','Nominee',2020),
('AMERICAN FACTORY','Documentary','Winner',2020),
('THE CAVE','Documentary','Nominee',2020),
('THE EDGE OF DEMOCRACY','Documentary','Nominee',2020),
('FOR SAMA','Documentary','Nominee',2020),
('HONEYLAND','Documentary','Nominee',2020),
('PARASITE','Movie','Winner',2020),
('FORD V FERRARI','Movie','Nominee',2020),
('THE IRISHMAN','Movie','Nominee',2020),
('JOJO RABBIT','Movie','Nominee',2020),
('JOKER','Movie','Nominee',2020),
('LITTLE WOMEN','Movie','Nominee',2020),
('1917','Movie','Nominee',2020),
('ONCE UPON A TIME...IN HOLLYWOOD','Movie','Nominee',2020),
('ANTHONY HOPKINS (The Father)','Actor','Winner',2021),
('RIZ AHMED (Sound of Metal)','Actor','Nominee',2021),
('CHADWICK BOSEMAN (Ma Rainey Black Bottom)','Actor','Nominee',2021),
('GARY OLDMAN (Mank)','Actor','Nominee',2021),
('STEVEN YEUN (Minari)','Actor','Nominee',2021),
('FRANCES MCDORMAND (Nomadland)','Actress','Winner',2021),
('VIOLA DAVIS (Ma Rainey Black Bottom)','Actress','Nominee',2021),
('ANDRA DAY (The United States vs. Billie Holiday)','Actress','Nominee',2021),
('VANESSA KIRBY (Pieces of a Woman)','Actress','Nominee',2021),
('CAREY MULLIGAN (Promising Young Woman)','Actress','Nominee',2021),
('MANK (Erik Messerschmidt)','Cinematography','Winner',2021),
('JUDAS AND THE BLACK MESSIAH (Sean Bobbitt)','Cinematography','Nominee',2021),
('NEWS OF THE WORLD (Dariusz Wolski)','Cinematography','Nominee',2021),
('NOMADLAND (Joshua James Richards)','Cinematography','Nominee',2021),
('THE TRIAL OF THE CHICAGO 7 (Phedon Papamichael)','Cinematography','Nominee',2021),
('Chloé Zhao (NOMADLAND)','Director','Winner',2021),
('Thomas Vinterberg (ANOTHER ROUND)','Director','Nominee',2021),
('David Fincher (MANK)','Director','Nominee',2021),
('Lee Isaac Chung (David Fincher)','Director','Nominee',2021),
('Emerald Fennell (PROMISING YOUNG WOMAN)','Director','Nominee',2021),
('FIGHT FOR YOU (Judas and the Black Messiah)','Music','Winner',2021),
('HEAR MY VOICE (The Trial of the Chicago 7)','Music','Nominee',2021),
('HUSAVIK (Eurovision Song Contest: The Story of Fire Saga)','Music','Nominee',2021),
('SEEN (The Life Ahead)','Music','Nominee',2021),
('SPEAK NOW (One Night in Miami...)','Music','Nominee',2021),
('TENET (Andrew Jackson, David Lee, Andrew Lockley and Scott Fisher)','Visual Effects','Winner',2021),
('LOVE AND MONSTERS (Matt Sloan, Genevieve Camilleri, Matt Everitt and Brian Cox)','Visual Effects','Nominee',2021),
('THE MIDNIGHT SKY (Matthew Kasmir, Christopher Lawrence, Max Solomon and David Watkins)','Visual Effects','Nominee',2021),
('MULAN (Sean Faden, Anders Langlands, Seth Maury and Steve Ingram)','Visual Effects','Nominee',2021),
('THE ONE AND ONLY IVAN (Nick Davis, Greg Fisher, Ben Jones and Santiago Colomo Martinez)','Visual Effects','Nominee',2021),
('MY OCTOPUS TEACHER','Documentary','Winner',2021),
('COLLECTIVE','Documentary','Nominee',2021),
('CRIP CAMP','Documentary','Nominee',2021),
('THE MOLE AGENT','Documentary','Nominee',2021),
('TIME','Documentary','Nominee',2021),
('NOMADLAND','Movie','Winner',2021),
('THE FATHER','Movie','Nominee',2021),
('JUDAS AND THE BLACK MESSIAH','Movie','Nominee',2021),
('MANK','Movie','Nominee',2021),
('MINARI','Movie','Nominee',2021),
('PROMISING YOUNG WOMAN','Movie','Nominee',2021),
('SOUND OF METAL','Movie','Nominee',2021),
('THE TRIAL OF THE CHICAGO 7','Movie','Nominee',2021),
('WILL SMITH (King Richard)','Actor','Winner',2022),
('JAVIER BARDEM (Being the Ricardos)','Actor','Nominee',2022),
('BENEDICT CUMBERBATCH (The Power of the Dog)','Actor','Nominee',2022),
('ANDREW GARFIELD (tick, tick...BOOM!)','Actor','Nominee',2022),
('DENZEL WASHINGTON (The Tragedy of Macbeth)','Actor','Nominee',2022),
('JESSICA CHASTAIN (The Eyes of Tammy Faye)','Actress','Winner',2022),
('OLIVIA COLMAN (The Lost Daughter)','Actress','Nominee',2022),
('PENÉLOPE CRUZ (Parallel Mothers)','Actress','Nominee',2022),
('NICOLE KIDMAN (Being the Ricardos)','Actress','Nominee',2022),
('KRISTEN STEWART (Spencer)','Actress','Nominee',2022),
('DUNE (Greig Fraser)','Cinematography','Winner',2022),
('NIGHTMARE ALLEY (Dan Laustsen)','Cinematography','Nominee',2022),
('THE POWER OF THE DOG (Ari Wegner)','Cinematography','Nominee',2022),
('THE TRAGEDY OF MACBETH (Bruno Delbonnel)','Cinematography','Nominee',2022),
('WEST SIDE STORY (Janusz Kaminski)','Cinematography','Nominee',2022),
('Jane Campion (THE POWER OF THE DOG)','Director','Winner',2022),
('Kenneth Branagh (BELFAST)','Director','Nominee',2022),
('Ryusuke Hamaguchi (DRIVE MY CAR)','Director','Nominee',2022),
('Paul Thomas Anderson (LICORICE PIZZA)','Director','Nominee',2022),
('Steven Spielberg (WEST SIDE STORY)','Director','Nominee',2022),
('NO TIME TO DIE (No Time to Die)','Music','Winner',2022),
('BE ALIVE (King Richard)','Music','Nominee',2022),
('DOS ORUGUITAS (Encanto)','Music','Nominee',2022),
('DOWN TO JOY (Belfast)','Music','Nominee',2022),
('SOMEHOW YOU DO (Four Good Days)','Music','Nominee',2022),
('DUNE (Paul Lambert, Tristan Myles, Brian Connor and Gerd Nefzer)','Visual Effects','Winner',2022),
('FREE GUY (Swen Gillberg, Bryan Grill, Nikos Kalaitzidis and Dan Sudick)','Visual Effects','Nominee',2022),
('NO TIME TO DIE (Charlie Noble, Joel Green, Jonathan Fawkner and Chris Corbould)','Visual Effects','Nominee',2022),
('SHANG-CHI AND THE LEGEND OF THE TEN RINGS (Christopher Townsend, Joe Farrell, Sean Noel Walker and Dan Oliver)','Visual Effects','Nominee',2022),
('SPIDER-MAN: NO WAY HOME (Kelly Port, Chris Waegner, Scott Edelstein and Dan Sudick)','Visual Effects','Nominee',2022),
('SUMMER OF SOUL (...OR, WHEN THE REVOLUTION COULD NOT BE TELEVISED)','Documentary','Winner',2022),
('ASCENSION','Documentary','Nominee',2022),
('ATTICA','Documentary','Nominee',2022),
('ATTICA','Documentary','Nominee',2022),
('WRITING WITH FIRE','Documentary','Nominee',2022),
('CODA','Movie','Winner',2022),
('BELFAST','Movie','Nominee',2022),
('DONT LOOK UP','Movie','Nominee',2022),
('DRIVE MY CAR','Movie','Nominee',2022),
('DUNE','Movie','Nominee',2022),
('KING RICHARD','Movie','Nominee',2022),
('LICORICE PIZZA','Movie','Nominee',2022),
('NIGHTMARE ALLEY','Movie','Nominee',2022),
('THE POWER OF THE DOG','Movie','Nominee',2022),
('WEST SIDE STORY','Movie','Nominee',2022),
('AUSTIN BUTLER (Elvis)','Actor','Nominee',2023),
('COLIN FARRELL (The Banshees of Inisherin)','Actor','Nominee',2023),
('BRENDAN FRASER (The Whale)','Actor','Nominee',2023),
('PAUL MESCAL (Aftersun)','Actor','Nominee',2023),
('BILL NIGHY (Living)','Actor','Nominee',2023),
('CATE BLANCHETT (Tár)','Actress','Nominee',2023),
('ANA DE ARMAS (Blonde)','Actress','Nominee',2023),
('ANDREA RISEBOROUGH (To Leslie)','Actress','Nominee',2023),
('MICHELLE WILLIAMS (The Fabelmans)','Actress','Nominee',2023),
('MICHELLE YEOH (Everything Everywhere All at Once)','Actress','Nominee',2023),
('ALL QUIET ON THE WESTERN FRONT (James Friend)','Cinematography','Nominee',2023),
('BARDO, FALSE CHRONICLE OF A HANDFUL OF TRUTHS (Darius Khondji)','Cinematography','Nominee',2023),
('ELVIS (Mandy Walker)','Cinematography','Nominee',2023),
('EMPIRE OF LIGHT (Roger Deakins)','Cinematography','Nominee',2023),
('TÁR (Florian Hoffmeister)','Cinematography','Nominee',2023),
('Martin McDonagh (THE BANSHEES OF INISHERIN)','Director','Nominee',2023),
('Daniel Kwan and Daniel Scheinert (EVERYTHING EVERYWHERE ALL AT ONCE)','Director','Nominee',2023),
('Steven Spielberg (THE FABELMANS)','Director','Nominee',2023),
('Todd Field (TÁR)','Director','Nominee',2023),
('Ruben Östlund (TRIANGLE OF SADNESS)','Director','Nominee',2023),
('APPLAUSE (Tell It like a Woman)','Music','Nominee',2023),
('HOLD MY HAND (Top Gun)','Music','Nominee',2023),
('LIFT ME UP (Black Panther)','Music','Nominee',2023),
('NAATU NAATU (RRR)','Music','Nominee',2023),
('THIS IS A LIFE (Everything Everywhere All at Once)','Music','Nominee',2023),
('ALL QUIET ON THE WESTERN FRONT (Frank Petzold, Viktor Müller, Markus Frank and Kamil Jafar)','Visual Effects','Nominee',2023),
('AVATAR: THE WAY OF WATER (Joe Letteri, Richard Baneham, Eric Saindon and Daniel Barrett)','Visual Effects','Nominee',2023),
('THE BATMAN (Dan Lemmon, Russell Earl, Anders Langlands and Dominic Tuohy)','Visual Effects','Nominee',2023),
('BLACK PANTHER: WAKANDA FOREVER (Geoffrey Baumann, Craig Hammack, R. Christopher White and Dan Sudick)','Visual Effects','Nominee',2023),
('TOP GUN: MAVERICK (Ryan Tudhope, Seth Hill, Bryan Litson and Scott R. Fisher)','Visual Effects','Nominee',2023),
('ALL THAT BREATHES','Documentary','Nominee',2023),
('ALL THE BEAUTY AND THE BLOODSHED','Documentary','Nominee',2023),
('FIRE OF LOVE','Documentary','Nominee',2023),
('A HOUSE MADE OF SPLINTERS','Documentary','Nominee',2023),
('NAVALNY','Documentary','Nominee',2023),
('ALL QUIET ON THE WESTERN FRONT','Movie','Nominee',2023),
('AVATAR: THE WAY OF WATER','Movie','Nominee',2023),
('THE BANSHEES OF INISHERIN','Movie','Nominee',2023),
('ELVIS','Movie','Nominee',2023),
('EVERYTHING EVERYWHERE ALL AT ONCE','Movie','Nominee',2023),
('THE FABELMANS','Movie','Nominee',2023),
('TÁR','Movie','Nominee',2023),
('TOP GUN: MAVERICK','Movie','Nominee',2023),
('TRIANGLE OF SADNESS','Movie','Nominee',2023),
('WOMEN TALKING','Movie','Nominee',2023);
